// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TranzactiiBancare.Migrations
{
    [DbContext(typeof(AppDbContextTranzactiiFinanciare))]
    [Migration("20251025173623_AddNetPersonalFields")]
    partial class AddNetPersonalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ImportHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sursa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UniqueKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ImportHistory");
                });

            modelBuilder.Entity("OcrKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Confidence")
                        .HasColumnType("integer");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OcrKnowledge");
                });

            modelBuilder.Entity("TranzactiiCommon.Models.TranzactieING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataAutorizarii")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataDecontarii")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataTranzactie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detalii")
                        .HasColumnType("text");

                    b.Property<bool>("EsteCredit")
                        .HasColumnType("boolean");

                    b.Property<bool>("EstePersonal")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsteProcesata")
                        .HasColumnType("boolean");

                    b.Property<string>("Merchant")
                        .HasColumnType("text");

                    b.Property<decimal?>("NetPersonal")
                        .HasColumnType("numeric");

                    b.Property<int?>("NrBeri")
                        .HasColumnType("integer");

                    b.Property<int?>("NrTigari")
                        .HasColumnType("integer");

                    b.Property<string>("NumarAutorizare")
                        .HasColumnType("text");

                    b.Property<string>("NumarCard")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Referinta")
                        .HasColumnType("text");

                    b.Property<decimal?>("SoldFinal")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Suma")
                        .HasColumnType("numeric");

                    b.Property<string>("SursaCard")
                        .HasColumnType("text");

                    b.Property<string>("TipTranzactie")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TranzactiiING");
                });
#pragma warning restore 612, 618
        }
    }
}
