// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TranzactiiBancare.Migrations
{
    [DbContext(typeof(AppDbContextTranzactiiFinanciare))]
    [Migration("20251005061119_AddOcrKnowledgeTable")]
    partial class AddOcrKnowledgeTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OcrKnowledge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OcrKnowledge");
                });

            modelBuilder.Entity("TranzactieING", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Categorie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataAutorizarii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataDecontarii")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataTranzactie")
                        .HasColumnType("datetime2");

                    b.Property<string>("Detalii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EsteCredit")
                        .HasColumnType("bit");

                    b.Property<string>("Merchant")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarAutorizare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumarCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Referinta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("SoldFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Suma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SursaCard")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipTranzactie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TranzactiiING");
                });
#pragma warning restore 612, 618
        }
    }
}
